import { mkdirSync, readFileSync, writeFileSync } from "fs";
import path from "path";
import { buildSchema, GraphQLSchema } from "graphql";
import {
  getLabelFieldFromDirectives,
  getRoleFromDirectives,
  getTokenConfigsFromDirectives,
  getTemplateFromDirectives,
} from "../a11y/directives";
import { humanizeTokens, Tok } from "../a11y/humanize";
import { renderTemplateSmart } from "../a11y/utils/renderTemplate";

type FixtureItem = {
  id: string;
  title: string;
  releaseYear: number;
  rating: number;
};

const ROOT = process.cwd();
const TYPE_NAME = "Movie";
const PAGE_PATH = "/movies";
const FIXTURE_PATH = path.join(ROOT, "demo", "movies.fixture.json");
const SCHEMA_PATH = path.join(ROOT, "demo", "schema.graphql");
const OUTPUT_DIR = path.join(ROOT, "generated");
const OUTPUT_JSON_PATH = path.join(OUTPUT_DIR, "a11y-spec.json");
const OUTPUT_TEST_PATH = path.join(OUTPUT_DIR, "a11y.generated.spec.ts");

const WEB_ROLE_MAP: Record<string, string> = {
  GROUP: "listitem",
  BUTTON: "button",
  LINK: "link",
  IMAGE: "img",
  STATUS: "status",
  ALERT: "alert",
};

function safe(value: unknown): string {
  return value == null ? "" : String(value);
}

function buildDescription(schema: GraphQLSchema, item: FixtureItem): string | undefined {
  const labelField = getLabelFieldFromDirectives(schema, TYPE_NAME);
  const config = getTokenConfigsFromDirectives(schema, TYPE_NAME);
  const template = getTemplateFromDirectives(schema, TYPE_NAME);
  const label = labelField ? safe(item[labelField as keyof FixtureItem]) : "";

  const tokens: Tok[] = config
    .map((token) => ({
      type: token.type,
      value: safe(item[token.field as keyof FixtureItem]),
      priority: token.priority ?? 0,
    }))
    .filter((token) => token.value.length > 0)
    .sort((a, b) => a.priority - b.priority);

  if (tokens.length === 0) return undefined;

  if (template) {
    const humanizedTokens = tokens.map((token) => ({
      type: token.type,
      value: humanizeTokens([token], config, "en", ", ", { forTemplate: true }),
    }));

    const templateTokens =
      label && template.includes("{title}")
        ? [{ type: "title", value: label }, ...humanizedTokens.filter((token) => token.type !== "title")]
        : humanizedTokens;

    return renderTemplateSmart(template, templateTokens, ", ");
  }

  return humanizeTokens(tokens, config, "en", ", ");
}

function buildSpec(schema: GraphQLSchema) {
  const labelField = getLabelFieldFromDirectives(schema, TYPE_NAME);
  const role = getRoleFromDirectives(schema, TYPE_NAME) ?? "GROUP";

  if (!labelField) {
    throw new Error(`${TYPE_NAME} is missing @a11yLabel`);
  }

  const items = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as FixtureItem[];
  const expectations = items.slice(0, 3).map((item) => {
    const name = safe(item[labelField as keyof FixtureItem]);
    const summary = buildDescription(schema, item);

    if (!name) {
      throw new Error(`${TYPE_NAME} fixture item is missing label field "${labelField}"`);
    }

    // Demo UI exposes one aria-label per item (accessible name), not title + describedby.
    const accessibleName = summary ?? name;

    return {
      role: WEB_ROLE_MAP[role] ?? "group",
      accessibleName,
    };
  });

  return {
    typeName: TYPE_NAME,
    path: PAGE_PATH,
    expectations,
  };
}

function writeJsonSpec(spec: ReturnType<typeof buildSpec>) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_JSON_PATH, JSON.stringify(spec, null, 2), "utf8");
}

function writePlaywrightSpec(spec: ReturnType<typeof buildSpec>) {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const file = `import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Generated by scripts/generate-a11y-tests.ts

const spec = ${JSON.stringify(spec, null, 2)} as const;

test(\`\${spec.typeName} accessibility contract\`, async ({ page }) => {
  await page.goto(spec.path);

  for (const expected of spec.expectations) {
    if (expected.role === "listitem") {
      // Native list items expose readable row text for screen readers here,
      // but do not produce a non-empty computed accessible name in Playwright.
      const element = page
        .getByRole(expected.role)
        .filter({ hasText: expected.accessibleName });

      await expect(element).toBeVisible();
      await expect(element).toContainText(expected.accessibleName);
      continue;
    }

    const element = page.getByRole(expected.role, {
      name: expected.accessibleName,
    });

    await expect(element).toBeVisible();
    await expect(element).toHaveAccessibleName(expected.accessibleName);
  }

  const axeResults = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa"])
    .analyze();

  expect(
    axeResults.violations,
    axeResults.violations.map((v) => \`\${v.id}: \${v.help}\`).join("\\n"),
  ).toEqual([]);
});
`;

  writeFileSync(OUTPUT_TEST_PATH, file, "utf8");
}

const schema = buildSchema(readFileSync(SCHEMA_PATH, "utf8"));
const spec = buildSpec(schema);

writeJsonSpec(spec);
writePlaywrightSpec(spec);

console.log(`Generated a11y specs for: ${spec.typeName}`);
